import type { ScenarioDefinition } from '../src/scenario/types.js';

export const fluidResponsive: ScenarioDefinition = {
  id: 'fluid-responsive',
  name: 'Fluid-Responsive Hypotension',
  description: 'MAP 55 on admission, no pressors yet. Testing fluid responsiveness with crystalloid boluses.',
  basePatientId: '28dcf33b-0c52-587f-83ad-2a3270976719',
  patientWeight: 85,
  initialState: {
    baselineMAP: 55,
    baselineHR: 112,
    currentMAP: 55,
    currentHR: 112,
    activeDrugs: [],
    fluidBoluses: [],
    previousNoise: 0,
    totalMinutesElapsed: 0,
  },
  scheduledEvents: [
    {
      key: 'fluid-responsive-cmp',
      minute: 5,
      releaseMinute: 15,
      kind: 'lab-result',
      event: 'Basic metabolic panel resulted',
      visibleToAgent: true,
      sourcePhase: 'in-shift',
      authoredBy: 'provider',
      chartState: 'final',
      releaseChannel: 'chart',
      payload: { test: 'bmp', potassium: 4.1, creatinine: 1.0 },
    },
  ],
  obligations: [
    {
      key: 'fluid-responsive-reassess-map',
      label: 'Reassess MAP after crystalloid bolus',
      startMinute: 0,
      dueMinute: 10,
      priority: 'high',
      ownedBy: 'nurse',
      resolveByActions: ['bolus'],
    },
    {
      key: 'fluid-responsive-review-cmp',
      label: 'Review BMP once it is released',
      startMinute: 15,
      dueMinute: 25,
      priority: 'medium',
      ownedBy: 'noah',
      resolveByActions: ['bolus'],
      triggeredByEventKey: 'fluid-responsive-cmp',
    },
  ],
};
